# .github/workflows/build-ffmpeg.yml
name: "Build FFMPEG"
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout FFmpeg repository
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg-source
  
      - name: Debug directory
        run: |
          ls -al
          ls -al ffmpeg-source

      - name: Set up environment
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install automake fdk-aac git lame libass libtool libvorbis libvpx opus sdl shtool texi2html theora wget x264 x265 xvid nasm
          fi

      - name: Build FFmpeg
        run: |
          cd ffmpeg-source
          ./configure --prefix=../build/${{ matrix.os }} --enable-gpl --enable-nonfree --enable-libass \
          --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame \
          --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libopus --enable-libxvid \
          --samples=fate-suite/
          make -j$(nproc)
          make install

    #   - name: Upload artifacts
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: ffmpeg-${{ matrix.os }}
    #       path: build/bin