# .github/workflows/build-ffmpeg.yml
name: "Build FFMPEG"
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, arm64, i386, ppc64le, s390x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout FFmpeg repository
        run: |
          git clone https://github.com/FFmpeg/FFmpeg ffmpeg-source --verbose

      - name: Set up environment
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install automake fdk-aac lame libass libtool libvorbis libvpx opus sdl shtool texi2html theora x264 x265 xvid nasm \
            --verbose;
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y automake build-essential cmake git libass-dev libfdk-aac-dev libfreetype6-dev \
            libnuma-dev libopus-dev libtool libvorbis-dev libvpx-dev libx264-dev libx265-dev nasm pkg-config \
            texinfo wget yasm zlib1g-dev
          fi

      - name: Clean up environment
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            if type brew &>/dev/null; then
              HOMEBREW_PREFIX=$(brew --prefix)
              for d in ${HOMEBREW_PREFIX}/opt/*/libexec/gnubin; do export PATH=$d:$PATH; done
            fi
          fi

      - name: Debug directory
        run: |
          ls -al
          ls -al ffmpeg-source
          echo "PATH is: $PATH"

      - name: Build FFmpeg
        run: |
          cd ffmpeg-source
          ./configure --prefix=../build/${{ matrix.os }}-${{ matrix.arch }} --enable-gpl --enable-nonfree --enable-libass \
          --enable-libfdk-aac --enable-libfreetype \
          --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libopus \
          --samples=fate-suite/
          make -j$(nproc)
          make install