# .github/workflows/build-ffmpeg.yml
name: "Build FFMPEG"
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout FFmpeg repository
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg-source

      - name: Set up environment
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install automake fdk-aac lame libass libtool libvorbis libvpx opus sdl shtool texi2html theora x264 x265 xvid nasm \
            --verbose;
          fi

      - name: Clean up macOS environment
        run: |
            if type brew &>/dev/null; then
              HOMEBREW_PREFIX=$(brew --prefix)
              for d in ${HOMEBREW_PREFIX}/opt/*/libexec/gnubin; do export PATH=$d:$PATH; done
            fi

      - name: Debug directory
        run: |
          ls -al
          ls -al ffmpeg-source
          echo "PATH is: $PATH"
          which uname
          which tr
          which mkdir
          which sed

      - name: Build FFmpeg
        run: |
          cd ffmpeg-source
          ./configure --prefix=../build/${{ matrix.os }} --enable-gpl --enable-nonfree --enable-libass \
          --enable-libfdk-aac --enable-libfreetype \
          --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libopus \
          --samples=fate-suite/
          make -j$(nproc)
          make install

    #   - name: Upload artifacts
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: ffmpeg-${{ matrix.os }}
    #       path: build/bin